# Generated by Django 5.1.6 on 2025-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formld',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='formld',
            name='uname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
