# Generated by Django 5.1.6 on 2025-03-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_formld_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formld',
            name='description',
        ),
    ]
