# Generated by Django 5.1.6 on 2025-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_formld_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formld',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic/'),
        ),
    ]
