# Generated by Django 5.1.6 on 2025-05-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formld',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
    ]
