# Generated by Django 5.1.6 on 2025-05-26 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_formld_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='<PASSWORD>', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='creator_profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='MLProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_file', models.FileField(upload_to='ml_projects/')),
                ('requirements', models.TextField(blank=True, help_text='List required packages or dependencies')),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='service.creatorprofile')),
            ],
        ),
    ]
