# Generated by Django 5.1.6 on 2025-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_mlproject_creator_delete_formld_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlproject',
            name='project_thumbnail',
            field=models.ImageField(default='project_thumbnail/default.png', upload_to='project_thumbnail/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic/'),
        ),
    ]
