# Generated by Django 5.1.6 on 2025-05-30 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_mlproject_project_thumbnail_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlproject',
            name='project_file',
        ),
        migrations.CreateModel(
            name='MLProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ml_projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='service.mlproject')),
            ],
        ),
    ]
