# Generated by Django 5.1.6 on 2025-05-30 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_mlproject_project_file_mlprojectfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlproject',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='mlprojectfile',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
