# Generated by Django 5.1.6 on 2025-05-30 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_mlproject_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlproject',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
