# Generated by Django 5.1.6 on 2025-05-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_mlproject_submitted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlprojectfile',
            old_name='submitted_at',
            new_name='submitted_att',
        ),
    ]
