# Generated by Django 5.1.6 on 2025-05-31 09:44

import cloudinary.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_rename_file_mlprojectfile_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlproject',
            name='project_thumbnail',
            field=cloudinary.models.CloudinaryField(default='project_thumbnails/default', max_length=255),
        ),
        migrations.AlterField(
            model_name='mlprojectfile',
            name='project_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='ml_projects/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_pics/defaultimg', max_length=255),
        ),
    ]
