# Generated by Django 5.1.6 on 2025-06-01 15:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_mlproject_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_pics/defaultimg', max_length=255, verbose_name='image'),
        ),
    ]
