# Generated by Django 5.1.6 on 2025-06-02 09:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlproject',
            name='project_thumbnail',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dnibeqxbz/image/upload/v1748684471/project_thumbnails/intvttjx8yra0wsbsorj.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dnibeqxbz/image/upload/v1748683657/default_eqwi5z.jpg', max_length=255, verbose_name='image'),
        ),
    ]
