# Generated by Django 5.1.6 on 2025-06-02 09:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_alter_mlproject_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlproject',
            name='project_thumbnail',
            field=cloudinary.models.CloudinaryField(default='project_thumbnails/intvttjx8yra0wsbsorj', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_eqwi5z', max_length=255, verbose_name='image'),
        ),
    ]
